turtle.setPosition(0, 0)
turtle.turnRight()
turtle.setSpeed(25)
basic.forever(function () {
    turtle.forward(2)
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnLeft()
    turtle.forward(2)
    turtle.turnLeft()
})
